name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v6

      - name: 📂 FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ftpupload.net
          username: if0_42806347
          password: SUA_NOVA_SENHA
          protocol: ftp
          port: 21
          server-dir: /htdocs/
          dangerous-clean-slate: true